# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
    - "wget https://s3.amazonaws.com/textblob/nltk_data.tar.gz"
    - "tar -xzvf nltk_data.tar.gz -C ~"
    # Temporary workaround for NLTK issue #824
    - "pip install setuptools<=9.1"

install:
  - pip install -U .

script: python run_tests.py
